eggs/urls.py
from django.urls import path
from . import views

app_name = "eggs"

urlpatterns = [
    path('records-details/', views.eggs_record_details, name="eggs_record_details"),
    path('add-egg-stock/', views.add_incoming_eggs, name="add_incoming_eggs"),
    path('update-incoming-stock/<id>/', views.update_incoming_stock, name="update_incoming_stock"),
    path('delete-incoming-stock/<id>/', views.delete_incoming_stock, name="delete_incoming_stock"),
    path('add-outgoing-egg-record/', views.add_outgoing_eggs, name="add_outgoing_eggs"),
    path('update-outgoing-egg-record/<id>/', views.update_outgoing_stock, name="update_outgoing_stock"),
    path('delete-outgoing-egg-record/<id>/', views.delete_outgoing_stock, name="delete_outgoing_stock"),

    path('generate_egg_slip/', views.generate_egg_slip, name="generate_egg_slip"),
]

employee/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.urls import path

app_name = 'employee'

urlpatterns = [
    path('employee_list', views.employee_list, name='employee_list'),

    path('employee_add/', views.employee_add, name='employee_add'),
    path('employee_update/<str:pk>/', views.employee_update, name='employee_update'),
    path('employee_delete/<id>/', views.employee_delete, name='employee_delete'),
    path('pay_salary/', views.pay_salary, name="pay_salary"),

    path('paid-salary-record/', views.paid_salary_record, name='paid_salary_record'),
    path('pay_salary/', views.pay_salary, name="pay_salary"),
    path('update-paid-salary/<id>/', views.update_salary_paid_record, name="update_salary_paid_record"),
    path('delete-paid-salary-record/<id>/', views.delete_salary_paid_record, name="delete_salary_paid_record"),

]

poultry_farm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eggs/', include('eggs.urls')),
    path('birds/', include('birds.urls')),
    path('employee/', include('employee.urls')),
    path('feed/', include('feed.urls')),
    path('medicine/', include('medicine.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expenses/', include('expenses.urls')),
    path('', views.homepage, name="homepage"),

    path('accounts/', include('django.contrib.auth.urls'))

]

employee/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class employee_data(models.Model):
    emp_name = models.CharField(max_length=20)
    emp_salary = models.IntegerField(default=0)
    emp_cnic = models.IntegerField(default=0)
    emp_num = models.IntegerField(default=0)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    emp_joining_date = models.DateTimeField()

    def __str__(self):
        return str(self.emp_name)


class SalaryPaid(models.Model):
    amount = models.IntegerField(default=0)
    date = models.DateTimeField()
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

employee/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

# Create your views here.


# @login_required(login_url='/accounts/login')
from employee.models import *


@login_required(login_url='/accounts/login')
def employee_list(request):
    Emp_data = employee_data.objects.all()
    total_emp = employee_data.objects.all().count()

    total_emp_salary = 0

    for EP in Emp_data:
        total_emp_salary = EP.emp_salary + total_emp_salary

    context = {'total_salary': total_emp_salary, 'TMO': Emp_data, 'total_emp': total_emp}

    return render(request, 'employee_list.html', context)


@login_required(login_url='/accounts/login')
def employee_add(request):
    Emp_data = employee_data()
    if request.method == 'POST':
        emp_name = request.POST.get("emp-name")
        emp_salary = request.POST.get("emp-salary")
        emp_cnic = request.POST.get("emp-cnic")
        emp_num = request.POST.get("emp-num")
        emp_Joining_date = request.POST.get("emp-Joining-date")

        Emp_data.emp_name = emp_name
        Emp_data.emp_salary = emp_salary
        Emp_data.emp_cnic = emp_cnic
        Emp_data.emp_num = emp_num
        Emp_data.emp_joining_date = emp_Joining_date

        Emp_data.updated_by = request.user
        Emp_data.save()

        return employee_list(request)

    return render(request, 'employee_add.html')


@login_required(login_url='/accounts/login')
def employee_update(request, pk):
    Emp_data = employee_data.objects.get(id=pk)

    if request.method == 'POST':
        emp_name = request.POST.get("emp-name")
        emp_salary = request.POST.get("emp-salary")
        emp_cnic = request.POST.get("emp-cnic")
        emp_num = request.POST.get("emp-num")
        emp_Joining_date = request.POST.get("emp-Joining-date")

        Emp_data.emp_name = emp_name
        Emp_data.emp_salary = emp_salary
        Emp_data.emp_cnic = emp_cnic
        Emp_data.emp_num = emp_num
        Emp_data.emp_joining_date = emp_Joining_date

        Emp_data.updated_by = request.user
        Emp_data.save()

        return employee_list(request)
    context = {'Emp_data': Emp_data}

    return render(request, 'employee_update.html', context)


@login_required(login_url='/accounts/login')
def employee_delete(request, id):
    obj = get_object_or_404(employee_data, id=id)
    obj.delete()
    return employee_list(request)

def paid_salary_record(request):
    salary_record = SalaryPaid.objects.all()
    total_paid_salary = 0
    for salary in salary_record.iterator():
        total_paid_salary = total_paid_salary + int(salary.amount)
    context = {"salary_record": salary_record, "total_paid_salary": total_paid_salary}
    return render(request, 'paid_salary_record.html', context)


@login_required(login_url='/accounts/login')
def pay_salary(request):
    if request.method == "POST":
        salary_paid = request.POST.get('salary_paid')
        date = request.POST.get('date')
        salary_obj = SalaryPaid(amount=salary_paid, date=date, updated_by=request.user)
        salary_obj.save()
        return paid_salary_record(request)
    return render(request, 'pay_salary.html', )

@login_required(login_url='/accounts/login')
def update_salary_paid_record(request, id):
    salary_record = SalaryPaid.objects.get(id=id)
    if request.method == 'POST':
        salary_paid = request.POST.get('salary_paid')
        date = request.POST.get('date')
        salary_record.amount = salary_paid
        salary_record.date = date
        salary_record.save()
        return paid_salary_record(request)
    context = {'salary_record': salary_record}
    return render(request, 'salary_record_update.html', context)

@login_required(login_url='/accounts/login')
def delete_salary_paid_record(request, id):
    salary_record = get_object_or_404(SalaryPaid, id=id)
    salary_record.delete()
    return paid_salary_record(request)

employee/templates/employee_add.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Employee </h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee Name</label>
                                <input type="text" class="form-control" name="emp-name"
                                       placeholder="Enter Employee Name">
                                {#                                <small class="text-muted">Enter Eggs Quantity</small>#}
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee Salary</label>
                                <input type="text" class="form-control" name="emp-salary"
                                       placeholder="Enter Employee Salary">
                                {#                                <small class="text-muted">Date of Entry</small>#}
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee CNIC</label>
                                <input type="text" class="form-control" name="emp-cnic"
                                       placeholder="Enter Employee CNIC">
                                {#                                <small class="text-muted">Enter Eggs Quantity</small>#}
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee Contact Number</label>
                                <input type="text" class="form-control" name="emp-num"
                                       placeholder="Enter Employee Number">
                                {#                                <small class="text-muted">Date of Entry</small>#}
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Joining Date </label>

                                <input type="datetime-local" class="form-control" name="emp-Joining-date" value="">

                                {#                                <small class="text-muted">Enter Eggs Quantity</small>#}
                            </div>
                        </div><!-- end col -->


                    </div>
                    <button type="submit" class="btn btn-secondary">Submit</button>

                </form>
            </div>
        </div>


    </div>
    </div>
    </div>

{% endblock %}

employee/templates/employee_list.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Employe List </h1>
    <div class="row">
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class="fas fa-user float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Total Employees</h6>
                <h3><span data-plugin="counterup">{{ total_emp }}</span></h3>
            </div>
        </div>
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class="fa fa-shopping-cart float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Total Employee Salary</h6>
                <h3><span data-plugin="counterup">{{ total_salary }}</span></h3>
            </div>
        </div>
        <div class="col-xl-2 col-md-6">
            <div class=" row">
                <a type="button" href="{% url "employee:employee_add" %}"
                   class="btn btn-secondary waves-effect waves-light width-md mt-3 mb-2">Add Employee
                    Stock
                </a>
                {#                                <a type="button" href=""#}
                {#                                   class="btn btn-secondary waves-effect waves-light width-md">Update Medicine</a>#}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="col-lg">
                    <div class="mt-2">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home"
                                   role="tab" aria-controls="home" aria-expanded="true">Employee List</a>
                            </li>
                            {#                            <li class="nav-item">#}
                            {#                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile"#}
                            {#                                   role="tab" aria-controls="profile">Egg Sales flow</a>#}
                            {#                            </li>#}
                        </ul>
                        <div class="tab-content text-muted" id="myTabContent">
                            <div role="tabpanel" class="tab-pane fade in active show" id="home"
                                 aria-labelledby="home-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Salary</th>
                                            <th>Joining Date</th>
                                            <th>Numuber</th>
                                            <th>CNIC</th>
                                            <th>Action</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for emp in TMO %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ emp.emp_name }}</td>
                                                <td>{{ emp.emp_salary }}</td>
                                                <td>{{ emp.emp_joining_date.date }}</td>
                                                <td>{{ emp.emp_num }}</td>
                                                <td>{{ emp.emp_cnic }}</td>

                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn btn" style="background: #F79824;"
                                                           href="{% url "employee:employee_update" emp.id %} ">Update</a>
                                                        <a type="button" class="btn " style="background: #981D20;"
                                                           href="{% url "employee:employee_delete" emp.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel"
                                 aria-labelledby="profile-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Quantity</th>
                                            <th>Date</th>
                                            <th>Amount Paid</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for outgoing in all_outgoings %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ outgoing.quantity }}</td>
                                                <td>{{ outgoing.date.date }}</td>
                                                <td>{{ outgoing.rate }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn btn-info"
                                                           href="{% url 'update-outgoing-egg-record' outgoing.id %}">Update</a>
                                                        <a type="button" class="btn btn-danger"
                                                           href="{% url 'delete-outgoing-egg-record' outgoing.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>




{% endblock %}

employee/templates/employee_update.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Employee </h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee Name</label>
                                <input type="text" class="form-control" name="emp-name" value="{{ Emp_data.emp_name }}"
                                       placeholder="Enter Employee Name">
                                {#                                <small class="text-muted">Enter Eggs Quantity</small>#}
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee Salary</label>
                                <input type="text" class="form-control" name="emp-salary" value="{{ Emp_data.emp_salary }}"
                                       placeholder="Enter Employee Salary">
                                {#                                <small class="text-muted">Date of Entry</small>#}
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee CNIC</label>
                                <input type="text" class="form-control" name="emp-cnic" value="{{ Emp_data.emp_cnic  }}"
                                       placeholder="Enter Employee CNIC">
                                {#                                <small class="text-muted">Enter Eggs Quantity</small>#}
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Employee Contact Number</label>
                                <input type="text" class="form-control" name="emp-num"   value="{{ Emp_data.emp_num }}"
                                       placeholder="Enter Employee Number">
                                {#                                <small class="text-muted">Date of Entry</small>#}
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Joining Date </label>

                                <input type="datetime-local" class="form-control" name="emp-Joining-date"value="{{Emp_data.emp_joining_date|date:'Y-m-d'}}T{{Emp_data.emp_joining_date|time:'H:i:s'}}">

                                {#                                <small class="text-muted">Enter Eggs Quantity</small>#}
                            </div>
                        </div><!-- end col -->


                    </div>
                    <button type="submit" class="btn btn-secondary">Submit</button>

                </form>
            </div>
        </div>


    </div>
    </div>
    </div>

{% endblock %}

employee/templates/paid_salary_record.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Paid Salary</h1>
    <div class="row">
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class="fas fa-dollar-sign float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Total Salary Paid Till Today</h6>
                <h3><span data-plugin="counterup">{{ total_paid_salary }}</span></h3>
            </div>
        </div>
        <div class="col-xl-2 col-md-6">
            <div class=" row">
                <a type="button" href="{% url "employee:pay_salary" %}"
                   class="btn btn-secondary waves-effect waves-light width-md mt-3 mb-2">Add Paid Salary
                </a>
{#                                <a type="button" href=""#}
{#                                   class="btn btn-secondary waves-effect waves-light width-md">Update Medicine</a>#}
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="col-lg">
                    <div class="mt-2">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home"
                                   role="tab" aria-controls="home" aria-expanded="true">Salary Record List</a>
                            </li>
                        </ul>
                        <div class="tab-content text-muted" id="myTabContent">
                            <div role="tabpanel" class="tab-pane fade in active show" id="home"
                                 aria-labelledby="home-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Amount Paid</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for salary in salary_record %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ salary.amount }}</td>
                                                <td>{{ salary.date.date }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn btn-info"
                                                           href="{% url "employee:update_salary_paid_record" salary.id %} ">Update</a>
                                                        <a type="button" class="btn btn-danger"
                                                           href="{% url "employee:delete_salary_paid_record" salary.id %} ">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel"
                                 aria-labelledby="profile-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Quantity</th>
                                            <th>Date</th>
                                            <th>Amount Paid</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for outgoing in all_outgoings %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ outgoing.quantity }}</td>
                                                <td>{{ outgoing.date.date }}</td>
                                                <td>{{ outgoing.rate }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn btn-info"
                                                           href="{% url 'update-outgoing-egg-record' outgoing.id %}">Update</a>
                                                        <a type="button" class="btn btn-danger"
                                                           href="{% url 'delete-outgoing-egg-record' outgoing.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>




{% endblock %}

employee/templates/pay_salary.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Salary Paid</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Salary Paid</label>
                                <input type="number" class="form-control" name="salary_paid" value="">
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Payment Date</label>
                                <input type="date" class="form-control" name="date" value="">
                            </div>
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

employee/templates/salary_record_update.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Update Paid Salary</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Salary Paid</label>
                                <input type="number" class="form-control" name="salary_paid" value="{{ salary_record.amount }}">
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Payment Date</label>
                                <input type="date" class="form-control" name="date" value="{{ salary_record.date |date:'Y-m-d'}}T{{salary_record.date|time:'H:i:s'}}">
                            </div>
                            <button type="submit" class="btn btn-primary float-right">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}