eggs/urls.py
from django.urls import path
from . import views

app_name = "eggs"

urlpatterns = [
    path('records-details/', views.eggs_record_details, name="eggs_record_details"),
    path('add-egg-stock/', views.add_incoming_eggs, name="add_incoming_eggs"),
    path('update-incoming-stock/<id>/', views.update_incoming_stock, name="update_incoming_stock"),
    path('delete-incoming-stock/<id>/', views.delete_incoming_stock, name="delete_incoming_stock"),
    path('add-outgoing-egg-record/', views.add_outgoing_eggs, name="add_outgoing_eggs"),
    path('update-outgoing-egg-record/<id>/', views.update_outgoing_stock, name="update_outgoing_stock"),
    path('delete-outgoing-egg-record/<id>/', views.delete_outgoing_stock, name="delete_outgoing_stock"),

    path('generate_egg_slip/', views.generate_egg_slip, name="generate_egg_slip"),
]

poultry_farm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eggs/', include('eggs.urls')),
    path('birds/', include('birds.urls')),
    path('employee/', include('employee.urls')),
    path('feed/', include('feed.urls')),
    path('medicine/', include('medicine.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expenses/', include('expenses.urls')),
    path('', views.homepage, name="homepage"),

    path('accounts/', include('django.contrib.auth.urls'))

]

eggs/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class IncomingEggStock(models.Model):
    quantity = models.IntegerField(default=0)
    date = models.DateTimeField()
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)


class OutgoingEggStock(models.Model):
    quantity = models.IntegerField(default=0)
    date = models.DateTimeField()
    rate = models.IntegerField(default=0)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

eggs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from eggs.models import IncomingEggStock, OutgoingEggStock

@login_required(login_url='/accounts/login')
def eggs_record_details(request):
    all_incomings = IncomingEggStock.objects.all()
    all_outgoings = OutgoingEggStock.objects.all()
    incoming_quantity = 0
    outgoing_quantity = 0
    for eggs in all_incomings.iterator():
        incoming_quantity = eggs.quantity + incoming_quantity

    for eggs in all_outgoings.iterator():
        outgoing_quantity = eggs.quantity + outgoing_quantity

    instock_eggs = incoming_quantity - outgoing_quantity

    context = {"instock_eggs": instock_eggs, "all_outgoings": all_outgoings, "outgoing_quantity": outgoing_quantity,
               "all_incomings": all_incomings}
    return render(request, 'eggs/eggs_record_details.html', context)

@login_required(login_url='/accounts/login')
def add_incoming_eggs(request):
    if request.method == 'POST':
        quantity = request.POST.get("eggs_quantity")
        date = request.POST.get("date")
        record = IncomingEggStock(quantity=quantity, date=date, updated_by=request.user)
        record.save()
        return  eggs_record_details(request)
        # return redirect(eggs_record_details)
    return render(request, 'eggs/add_incoming_eggs.html', )

@login_required(login_url='/accounts/login')
def update_incoming_stock(request, id):
    update_record = IncomingEggStock.objects.get(id=id)
    if request.method == 'POST':
        quantity = request.POST.get("eggs_quantity")
        date = request.POST.get("date")
        update_record.quantity = quantity
        update_record.date = date
        update_record.save()
        return  eggs_record_details(request)
    return render(request, 'eggs/update_incoming_eggs.html', {"update_record": update_record})

@login_required(login_url='/accounts/login')
def delete_incoming_stock(request, id):
    obj = get_object_or_404(IncomingEggStock, id=id)
    obj.delete()
    return  eggs_record_details(request)

@login_required(login_url='/accounts/login')
def add_outgoing_eggs(request):
    if request.method == 'POST':
        quantity = request.POST.get("eggs_quantity")
        date = request.POST.get("date")
        amount = request.POST.get("amount")
        outgoing_record = OutgoingEggStock(quantity=quantity, date=date, rate=amount, updated_by=request.user)
        outgoing_record.save()
        return  eggs_record_details(request)
    return render(request, 'eggs/add_outgoing_eggs.html', )

@login_required(login_url='/accounts/login')
def update_outgoing_stock(request, id):
    update_record = OutgoingEggStock.objects.get(id=id)
    if request.method == 'POST':
        quantity = request.POST.get("eggs_quantity")
        date = request.POST.get("date")
        amount = request.POST.get("amount")
        update_record.quantity = quantity
        update_record.date = date
        update_record.rate = amount
        update_record.save()
        return  eggs_record_details(request)
    print(update_record.quantity)
    return render(request, 'eggs/update_outgoing_stock.html', {"update_record": update_record})

@login_required(login_url='/accounts/login')
def delete_outgoing_stock(request, id):
    obj = get_object_or_404(OutgoingEggStock, id=id)
    obj.delete()
    return  eggs_record_details(request)

@login_required(login_url='/accounts/login')
def generate_egg_slip(request):
    if request.method == "POST":
        from_date = request.POST.get("from_date")
        to_date = request.POST.get("to_date")

        all_incomings = IncomingEggStock.objects.filter(date__range=(from_date, to_date))
        all_outgoings = OutgoingEggStock.objects.filter(date__range=(from_date, to_date))
        incoming_quantity = 0
        outgoing_quantity = 0
        for eggs in all_incomings.iterator():
            incoming_quantity = eggs.quantity + incoming_quantity

        for eggs in all_outgoings.iterator():
            outgoing_quantity = eggs.quantity + outgoing_quantity

        instock_eggs = incoming_quantity - outgoing_quantity

        context = {"instock_eggs": instock_eggs, "all_outgoings": all_outgoings, "outgoing_quantity": outgoing_quantity,
                   "all_incomings": all_incomings}
        return render(request, 'eggs/eggs_record_details.html', context)

    return render(request, 'eggs/generate_egg_slip.html', )

eggs/templates/eggs/add_incoming_eggs.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Eggs Stock</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Eggs Quantity</label>
                                <input type="text" class="form-control" name="eggs_quantity" required
                                       placeholder="Eggs Quantity">
                                <small class="text-muted">Enter Eggs Quantity</small>
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date" value="" required>
                                <small class="text-muted">Date of Entry</small>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>


    </div>
    </div>
    </div>

{% endblock %}

eggs/templates/eggs/add_outgoing_eggs.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Eggs Sales Record</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-4">
                            <div class="form-group">
                                <label>Eggs Quantity</label>
                                <input type="text" class="form-control" name="eggs_quantity" required
                                       placeholder="Eggs Quantity" required>
                                <small class="text-muted">Enter Eggs Quantity</small>
                            </div>
                        </div><!-- end col -->
                        <div class="col-xl-4">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date" required>
                                <small class="text-muted">Date of Entry</small>
                            </div>
                        </div>
                        <div class="col-xl-4">
                            <div class="form-group">
                                <label>Eggs Quantity</label>
                                <input type="text" class="form-control" name="amount" required
                                       placeholder="Amount received" required>
                                <small class="text-muted">Enter the amount received</small>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Submit</button>
                        </div><!-- end col -->
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

eggs/templates/eggs/eggs_record_details.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Eggs</h1>
    <div class="row">
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class="fa fa-egg float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Eggs Instock</h6>
                <h3><span data-plugin="counterup">{{ instock_eggs }}</span></h3>
            </div>
        </div>
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class="icon-rocket float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Eggs Sold</h6>
                <h3><span data-plugin="counterup">{{ outgoing_quantity }}</span></h3>
            </div>
        </div>
        <div class="col-xl-2 col-md-6">
            <div class=" row">
                <a type="button" href="{% url 'eggs:add_incoming_eggs' %}"
                   class="btn btn-secondary waves-effect waves-light width-md mt-3 mb-2">Add Eggs
                    Stock
                </a>
                <a type="button" href="{% url 'eggs:add_outgoing_eggs' %}"
                   class="btn btn-secondary waves-effect waves-light width-md">Add Out Going</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="col-lg">
                    <div class="mt-2">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home"
                                   role="tab" aria-controls="home" aria-expanded="true">In Stock Record</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile"
                                   role="tab" aria-controls="profile">Egg Sales flow</a>
                            </li>
                        </ul>
                        <div class="tab-content text-muted" id="myTabContent">
                            <div role="tabpanel" class="tab-pane fade in active show" id="home"
                                 aria-labelledby="home-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Quantity</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for incoming in all_incomings %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ incoming.quantity }}</td>
                                                <td>{{ incoming.date.date }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn " style="background-color: #F79824"
                                                           href="{% url 'eggs:update_incoming_stock' incoming.id %}">Update</a>
                                                        <a type="button" class="btn " style="background-color: #981D20"
                                                           href="{% url 'eggs:delete_incoming_stock' incoming.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel"
                                 aria-labelledby="profile-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Quantity</th>
                                            <th>Date</th>
                                            <th>Amount Paid</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for outgoing in all_outgoings %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ outgoing.quantity }}</td>
                                                <td>{{ outgoing.date.date }}</td>
                                                <td>{{ outgoing.rate }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn btn-info"
                                                           href="{% url 'eggs:update_outgoing_stock' outgoing.id %}">Update</a>
                                                        <a type="button" class="btn btn-danger"
                                                           href="{% url 'eggs:delete_outgoing_stock' outgoing.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>




{% endblock %}

eggs/templates/eggs/generate_egg_slip.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1> Generate Eggs Slip</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>From Date</label>
                                <input type="date" class="form-control" name="from_date" value="" required>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="date" class="form-control" name="to_date" value="" required>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

eggs/templates/eggs/update_incoming_eggs.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Eggs Stock</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Eggs Quantity</label>
                                <input type="text" class="form-control" name="eggs_quantity"
                                       placeholder="Eggs Quantity" required value="{{ update_record.quantity }}">
                                <small class="text-muted">Enter Eggs Quantity</small>
                            </div>
                        </div><!-- end col -->



                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date"
                                       value="{{ update_record.date |date:'Y-m-d'}}T{{update_record.date|time:'H:i:s'}}">
                                <small class="text-muted">Date of Entry</small>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

eggs/templates/eggs/update_outgoing_stock.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Eggs Stock</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-4">
                            <div class="form-group">
                                <label>Eggs Quantity</label>
                                <input type="text" class="form-control" name="eggs_quantity"
                                       placeholder="Eggs Quantity" required value="{{ update_record.quantity }}">
                                <small class="text-muted">Enter Eggs Quantity</small>
                            </div>
                        </div><!-- end col -->
                        <div class="col-xl-4">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date"
                                       value="{{ update_record.date |date:'Y-m-d'}}T{{update_record.date|time:'H:i:s'}}">
                                <small class="text-muted">Date of Entry</small>
                            </div>
                        </div>
                        <div class="col-xl-4">
                            <div class="form-group">
                                <label>Eggs Quantity</label>
                                <input type="text" class="form-control" name="amount"
                                       placeholder="Amount received"  value="{{ update_record.rate }}" required>
                                <small class="text-muted">Enter the amount received</small>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Update</button>
                        </div><!-- end col -->
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}