accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    path('logout/', views.logout_page, name='logout'),
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),

     path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
     name="reset_password"),

    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset/done/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
        name="password_reset_complete"),

    # path('reset_passwrd_comord_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset_passwoplete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]


    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    # path('reset_passwrd_comord_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset_passwoplete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

birds/urls.py
from django.urls import path, include
from . import views

app_name = 'birds'


urlpatterns = [
    path('records/', views.birds_record_view, name="birds_record_view"),
    path('add-birds/', views.add_more_alive_birds, name="add-more-alive-bird"),
    path('update-alive-birds-record/<id>/', views.update_more_alive_birds, name="update_more_alive_birds"),
    path('delete-alive-birds-record/<id>/', views.delete_alive_birds_record, name="delete_alive_birds_record"),
    path('add-birds-death/', views.add_birds_deaths, name="add_birds_deaths"),
    path('update-birds-death-record/<id>/', views.update_birds_deaths, name="update_birds_deaths"),
    path('delete-dead-birds-record/<id>/', views.delete_dead_birds_record, name="delete_dead_birds_record"),

    path('generate_birds_slip/', views.generate_birds_slip, name="generate_birds_slip"),

]

eggs/urls.py
from django.urls import path
from . import views

app_name = "eggs"

urlpatterns = [
    path('records-details/', views.eggs_record_details, name="eggs_record_details"),
    path('add-egg-stock/', views.add_incoming_eggs, name="add_incoming_eggs"),
    path('update-incoming-stock/<id>/', views.update_incoming_stock, name="update_incoming_stock"),
    path('delete-incoming-stock/<id>/', views.delete_incoming_stock, name="delete_incoming_stock"),
    path('add-outgoing-egg-record/', views.add_outgoing_eggs, name="add_outgoing_eggs"),
    path('update-outgoing-egg-record/<id>/', views.update_outgoing_stock, name="update_outgoing_stock"),
    path('delete-outgoing-egg-record/<id>/', views.delete_outgoing_stock, name="delete_outgoing_stock"),

    path('generate_egg_slip/', views.generate_egg_slip, name="generate_egg_slip"),
]

employee/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.urls import path

app_name = 'employee'

urlpatterns = [
    path('employee_list', views.employee_list, name='employee_list'),

    path('employee_add/', views.employee_add, name='employee_add'),
    path('employee_update/<str:pk>/', views.employee_update, name='employee_update'),
    path('employee_delete/<id>/', views.employee_delete, name='employee_delete'),
    path('pay_salary/', views.pay_salary, name="pay_salary"),

    path('paid-salary-record/', views.paid_salary_record, name='paid_salary_record'),
    path('pay_salary/', views.pay_salary, name="pay_salary"),
    path('update-paid-salary/<id>/', views.update_salary_paid_record, name="update_salary_paid_record"),
    path('delete-paid-salary-record/<id>/', views.delete_salary_paid_record, name="delete_salary_paid_record"),

]

feed/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.urls import path

app_name = 'feed'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('feed_details/', views.feed_details, name='feed_details'),

    path('feed_add/', views.feed_add, name='feed_add'),
    path('feed_update/<str:pk>/', views.feed_update, name='feed_update'),
    path('Feed_delete/<id>/', views.Feed_delete, name='Feed_delete'),

    path('feed_s13_out_add/', views.feed_s13_out_add, name='feed_s13_out_add'),
    path('feed_s13_out_updaate/<str:pk>/', views.feed_s13_out_updaate, name='feed_s13_out_updaate'),
    path('feed_s13_out_delete/<id>/', views.feed_s13_out_delete, name='feed_s13_out_delete'),

    path('feeds16_in_add/', views.feeds16_in_add, name='feeds16_in_add'),
    path('feeds16_in_update/<str:pk>/', views.feeds16_in_update, name='feeds16_in_update'),
    path('feeds16_in_delete/<id>/', views.feeds16_in_delete, name='feeds16_in_delete'),

    path('feeds16_out_add/', views.feeds16_out_add, name='feeds16_out_add'),
    path('feeds16_out_update/<str:pk>/', views.feeds16_out_update, name='feeds16_out_update'),
    path('feeds16_out_delete/<id>/', views.feeds16_out_delete, name='feeds16_out_delete'),

    path('generate_feed_slip/', views.generate_feed_slip, name="generate_feed_slip"),
    # path('view_feed_slip/', views.view_feed_slip, name="view_feed_slip"),

]

poultry_farm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eggs/', include('eggs.urls')),
    path('birds/', include('birds.urls')),
    path('employee/', include('employee.urls')),
    path('feed/', include('feed.urls')),
    path('medicine/', include('medicine.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expenses/', include('expenses.urls')),
    path('', views.homepage, name="homepage"),

    path('accounts/', include('django.contrib.auth.urls'))

]

templates/baseTeamplate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Dashboard | Uplon - Responsive Bootstrap 4 Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Responsive bootstrap 4 admin template" name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'sm-logo-2.png' %}">
{#                  <img src="{% static 'sm-logo.PNG' %}" style="width: 70%">#}

    <link href="{% static 'libs/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>

    <link href="{% static 'libs/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'libs/datatables/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'libs/datatables/select.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>


    <!-- App css -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" id="bootstrap-stylesheet"/>
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/app.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet"/>
    <link href="{% static 'sj.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet"/>

    {#    <link href="{% static 'js/app.min.js' %}" rel="stylesheet" type="text/css" id="app-stylesheet"/>#}
    {#    <link href="{% static 'js/vendor.min.js' %}" rel="stylesheet" type="text/css" id="app-stylesheet"/>#}

</head>
<body>

<div id="wrapper">

    <!-- Topbar Start -->
    <div class="navbar-custom">
        <ul class="list-unstyled topnav-menu float-right mb-0">

            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown"
                   href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    {#                    <span class="d-none d-sm-inline-block ml-1 font-weight-medium">Alex M.</span>#}
                    <span class="hello-msg d-none d-sm-inline-block ml-1 font-weight-medium" style="color: white; "> Hello-{{ request.user }}</span>

                    <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                    <!-- item-->
                    <div class="dropdown-header noti-title">
                        <h6 class="text-overflow text-white m-0">Welcome !</h6>
                    </div>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-account-outline"></i>
                        <span>Profile</span>
                    </a>


                    <div class="dropdown-divider"></div>

                    <!-- item-->
                    <a href="{% url "accounts:logout" %}" class="dropdown-item notify-item">
                        <i class="mdi mdi-logout-variant"></i>
                        <span>Logout</span>
                    </a>

                    </a>

                </div>
            </li>

        </ul>

        <!-- LOGO -->
        <div class="logo-box">
            <a href="#" class="logo text-center logo-dark">
                        <span class="logo-lg">
                  <img src="{% static 'logo.jpeg' %}" style="width:100%">
                            <!-- <span class="logo-lg-text-dark">Uplon</span> -->
                        </span>
                <span class="logo-sm">
                            <!-- <span class="logo-lg-text-dark">U</span> -->
                  <img src="{% static 'sm-logo-2.png' %}" style="width: 70%">
                        </span>
            </a>

            <a href="#" class="logo text-center logo-light">
                        <span class="logo-lg">
                            <img src="{% static 'images/logo-light.png' %}" alt="" height="22">
                            <!-- <span class="logo-lg-text-dark">Uplon</span> -->
                        </span>
                <span class="logo-sm">
                            <!-- <span class="logo-lg-text-dark">U</span> -->
                            <img src="{% static 'images/logo-sm-light.png' %}" alt="" height="24">
                        </span>
            </a>
        </div>

        <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
            <li>
                <button class="button-menu-mobile waves-effect waves-light">
                    <i class="mdi mdi-menu"></i>
                </button>
            </li>

        </ul>
    </div>
    <!-- end Topbar -->


    <!-- ========== Left Sidebar Start ========== -->
    <div class="left-side-menu">

        <div class="slimscroll-menu">

            <!--- Sidemenu -->
            <div id="sidebar-menu">

                <ul class="metismenu" id="side-menu">

                    <li class="menu-title">Navigation</li>

                    {#                    <li>#}
                    {#                        <a href="{% url 'dashboard:homepage' %}">#}
                    {#                            <i class="mdi mdi-view-dashboard"></i>#}
                    {#                            <span> Dashboard </span>#}
                    {#                        </a>#}
                    {#                    </li>#}
                    <li>
                        <a href="javascript: void(0);">
                            <i class="typcn typcn-social-twitter"></i>
                            <span> Birds </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li><a href="{% url "birds:birds_record_view" %}">Birds Record</a></li>
                            <li><a href="{% url 'birds:add-more-alive-bird' %}">Add Birds Record</a></li>
                            <li><a href="{% url 'birds:add_birds_deaths' %}">Add Birds Death Record</a></li>
                            <li><a href="{% url 'birds:generate_birds_slip' %}">Generate Slip</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="javascript: void(0);">
                            <i class="fas fa-egg"></i>
                            <span> Eggs </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li><a href="{% url "eggs:eggs_record_details" %}">Eggs Record</a></li>
                            <li><a href="{% url 'eggs:add_incoming_eggs' %}">Add Eggs Incoming Record</a></li>
                            <li><a href="{% url 'eggs:add_outgoing_eggs' %}">Add Eggs Sales Record</a></li>
                            <li><a href="{% url 'eggs:generate_egg_slip' %}">Generate Slip</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="javascript: void(0);">
                            <i class="fas fa-users"></i>
                            <span> Employees </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li><a href="{% url "employee:employee_list" %}">Employees List</a></li>
                            <li><a href="{% url 'employee:employee_add' %}">Add Employee</a></li>
                            <li><a href="{% url 'employee:paid_salary_record' %}">Paid Salary</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="javascript: void(0);">
                            <i class="fas fa-cloud-meatball"></i>
                            <span> Feed </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li><a href="{% url 'feed:feed_details' %}">Feed Details</a></li>
                            <li><a href="{% url 'feed:feed_add' %}">Add S13-Feed</a></li>
                            <li><a href="{% url 'feed:feeds16_in_add' %}">Add S16-Feed</a></li>
                            <li><a href="{% url 'feed:generate_feed_slip' %}">generate_feed_slip</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="javascript: void(0);">
                            <i class="fas fa-capsules"></i>
                            <span> Medicine </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li><a href="{% url 'medicine:medicine_list' %}">Medicine Details</a></li>
                            <li><a href="{% url 'medicine:medicine_add' %}">Add Medicine Record</a></li>
                            <li><a href="{% url 'medicine:generate_medicine_slip' %}">Generate Slip</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="javascript: void(0);">
                            <i class="fas fa-dollar-sign"></i>
                            <span> Expenses </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li><a href="{% url "expense:expenses_view" %}">All Expenses</a></li>
                            <li><a href="{% url "expense:add_other_expenses" %}">Add Expense</a></li>
                            <li><a href="{% url 'expense:generated_expense' %}">Generate Expense</a></li>
                        </ul>
                    </li>

                </ul>

            </div>
            <!-- End Sidebar -->

            <div class="clearfix"></div>

        </div>
        <!-- Sidebar -left -->

    </div>
    <!-- Left Sidebar End -->
    <!-- ============================================================== -->
    <!-- Start Page Content here -->
    <!-- ============================================================== -->

    <div class="content-page">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    2016 - 2019 &copy; Uplon theme by <a href="">Coderthemes</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->


</div>


<!-- Vendor js -->
<script src="{% static 'js/vendor.min.js' %}"></script>

<!--Morris Chart-->
<script src="{% static 'libs/morris-js/morris.min.js' %}"></script>
<script src="{% static 'libs/raphael/raphael.min.js' %}"></script>


<!-- Datatable plugin js -->
<script src="{% static 'libs/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="{% static 'libs/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static 'libs/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables/buttons.bootstrap4.min.js' %}"></script>

<script src="{% static 'libs/jszip/jszip.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/vfs_fonts.js' %}"></script>

<script src="{% static 'libs/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables/buttons.print.min.js' %}"></script>

<script src="{% static 'libs/datatables/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'libs/datatables/dataTables.select.min.js' %}"></script>

<!-- Datatables init -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<!-- Dashboard init js-->
<script src="{% static 'js/pages/dashboard.init.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>