birds/urls.py
from django.urls import path, include
from . import views

app_name = 'birds'


urlpatterns = [
    path('records/', views.birds_record_view, name="birds_record_view"),
    path('add-birds/', views.add_more_alive_birds, name="add-more-alive-bird"),
    path('update-alive-birds-record/<id>/', views.update_more_alive_birds, name="update_more_alive_birds"),
    path('delete-alive-birds-record/<id>/', views.delete_alive_birds_record, name="delete_alive_birds_record"),
    path('add-birds-death/', views.add_birds_deaths, name="add_birds_deaths"),
    path('update-birds-death-record/<id>/', views.update_birds_deaths, name="update_birds_deaths"),
    path('delete-dead-birds-record/<id>/', views.delete_dead_birds_record, name="delete_dead_birds_record"),

    path('generate_birds_slip/', views.generate_birds_slip, name="generate_birds_slip"),

]

eggs/urls.py
from django.urls import path
from . import views

app_name = "eggs"

urlpatterns = [
    path('records-details/', views.eggs_record_details, name="eggs_record_details"),
    path('add-egg-stock/', views.add_incoming_eggs, name="add_incoming_eggs"),
    path('update-incoming-stock/<id>/', views.update_incoming_stock, name="update_incoming_stock"),
    path('delete-incoming-stock/<id>/', views.delete_incoming_stock, name="delete_incoming_stock"),
    path('add-outgoing-egg-record/', views.add_outgoing_eggs, name="add_outgoing_eggs"),
    path('update-outgoing-egg-record/<id>/', views.update_outgoing_stock, name="update_outgoing_stock"),
    path('delete-outgoing-egg-record/<id>/', views.delete_outgoing_stock, name="delete_outgoing_stock"),

    path('generate_egg_slip/', views.generate_egg_slip, name="generate_egg_slip"),
]

poultry_farm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eggs/', include('eggs.urls')),
    path('birds/', include('birds.urls')),
    path('employee/', include('employee.urls')),
    path('feed/', include('feed.urls')),
    path('medicine/', include('medicine.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expenses/', include('expenses.urls')),
    path('', views.homepage, name="homepage"),

    path('accounts/', include('django.contrib.auth.urls'))

]

birds/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class AliveBirdsRecords(models.Model):
    birds_added = models.IntegerField(default=0)
    date = models.DateTimeField()
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)


class DeathBirdsRecords(models.Model):
    birds_died = models.IntegerField(default=0)
    date = models.DateTimeField()
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

birds/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import *


# Create your views here.
@login_required(login_url='/accounts/login')
def birds_record_view(request):
    alive_birds = AliveBirdsRecords.objects.all()
    dead_birds = DeathBirdsRecords.objects.all()
    alive_birds_count = 0
    dead_birds_count = 0
    for birds in alive_birds.iterator():
        alive_birds_count = birds.birds_added + alive_birds_count
    for birds in dead_birds.iterator():
        dead_birds_count = birds.birds_died + dead_birds_count

    total_birds = alive_birds_count - dead_birds_count
    context = {"total_birds": total_birds, "dead_birds_count": dead_birds_count, "alive_birds": alive_birds,
               "dead_birds": dead_birds,
               "alive_birds_count": alive_birds_count}
    return render(request, 'birds/birds_record_view.html', context)
@login_required(login_url='/accounts/login')
def generate_birds_slip(request):
    if request.method == "POST":
        from_date = request.POST.get("from_date")
        to_date = request.POST.get("to_date")
        alive_birds = AliveBirdsRecords.objects.filter(date__range=(from_date, to_date))
        dead_birds = DeathBirdsRecords.objects.filter(date__range=(from_date, to_date))
        alive_birds_count = 0
        dead_birds_count = 0
        for birds in alive_birds.iterator():
            alive_birds_count = birds.birds_added + alive_birds_count
        for birds in dead_birds.iterator():
            dead_birds_count = birds.birds_died + dead_birds_count

        total_birds = alive_birds_count - dead_birds_count
        context = {"total_birds": total_birds, "dead_birds_count": dead_birds_count, "alive_birds": alive_birds,
                   "dead_birds": dead_birds,
                   "alive_birds_count": alive_birds_count}
        return render(request, 'birds/birds_record_view.html', context)

    return render(request, 'birds/generate_birds_slip.html',)

@login_required(login_url='/accounts/login')
def add_more_alive_birds(request):
    if request.method == 'POST':
        no_of_birds = request.POST.get("no_of_birds")
        date = request.POST.get("date")
        record = AliveBirdsRecords(birds_added=no_of_birds, date=date, updated_by=request.user)
        record.save()
        return  birds_record_view(request)
        # return redirect(birds_record_view)
    return render(request, 'birds/add_more_alive_birds.html')

@login_required(login_url='/accounts/login')
def update_more_alive_birds(request, id):
    update_record = AliveBirdsRecords.objects.get(id=id)
    if request.method == 'POST':
        no_of_birds = request.POST.get("no_of_birds")
        date = request.POST.get("date")
        update_record.birds_added = no_of_birds
        update_record.date = date
        update_record.save()
        return  birds_record_view(request)
    return render(request, 'birds/update_more_alive_birds.html', {"update_record": update_record})

@login_required(login_url='/accounts/login')
def delete_alive_birds_record(request, id):
    obj = get_object_or_404(AliveBirdsRecords, id=id)
    obj.delete()
    return birds_record_view(request)

@login_required(login_url='/accounts/login')
def add_birds_deaths(request):
    if request.method == 'POST':
        no_of_birds = request.POST.get("no_of_birds")
        date = request.POST.get("date")
        record = DeathBirdsRecords(birds_died=no_of_birds, date=date, updated_by=request.user)
        record.save()
        return  birds_record_view(request)
    return render(request, 'birds/add_birds_deaths.html')

@login_required(login_url='/accounts/login')
def update_birds_deaths(request, id):
    update_record = DeathBirdsRecords.objects.get(id=id)
    if request.method == 'POST':
        no_of_birds = request.POST.get("no_of_birds")
        date = request.POST.get("date")
        update_record.birds_died = no_of_birds
        update_record.date = date
        update_record.save()
        return  birds_record_view(request)
    return render(request, 'birds/update_birds_death.html', {"update_record": update_record})

@login_required(login_url='/accounts/login')
def delete_dead_birds_record(request, id):
    obj = get_object_or_404(DeathBirdsRecords, id=id)
    obj.delete()
    return birds_record_view(request)

birds/templates/birds/add_birds_deaths.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Death Record</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>No of Birds</label>
                                <input type="text" class="form-control" name="no_of_birds" required>
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date" value="" required>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

birds/templates/birds/add_more_alive_birds.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Add Birds</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>No of Birds</label>
                                <input type="text" class="form-control" name="no_of_birds" required>
                                <small class="text-muted">Enter Number of New Birds</small>
                            </div>
                        </div><!-- end col -->

                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date" value="" required>
                                <small class="text-muted">Date of Entry</small>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

birds/templates/birds/birds_record_view.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Birds</h1>
    <div class="row">
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class=" fab fa-earlybirds float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Total Birds</h6>
                <h3><span data-plugin="counterup">{{ total_birds }}</span></h3>
            </div>
        </div>
        <div class="col-xl-5 col-md-6">
            <div class="card-box tilebox-two">
                <i class="fas fa-book-dead float-right text-muted"></i>
                <h6 class="text-success text-uppercase">Total Deaths</h6>
                <h3><span data-plugin="counterup">{{ dead_birds_count }}</span></h3>
            </div>
        </div>
        <div class="col-xl-2 col-md-6">
            <div class=" row">
                <a type="button" href="{% url 'birds:add-more-alive-bird' %}"
                   class="btn btn-secondary waves-effect waves-light width-md mt-3 mb-2">Add More
                    Birds
                </a>
                <a type="button" href="{% url 'birds:add_birds_deaths' %}"
                   class="btn btn-secondary waves-effect waves-light width-md">Add Death Record</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="col-lg">
                    <div class="mt-2">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home"
                                   role="tab" aria-controls="home" aria-expanded="true">Birds Records</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile"
                                   role="tab" aria-controls="profile">Birds Death Records</a>
                            </li>
                        </ul>
                        <div class="tab-content text-muted" id="myTabContent">
                            <div role="tabpanel" class="tab-pane fade in active show" id="home"
                                 aria-labelledby="home-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>N.O of Birds</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for alive in alive_birds %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ alive.birds_added }}</td>
                                                <td>{{ alive.date.date }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn "  style="background-color: #F79824"
                                                           href="{% url 'birds:update_more_alive_birds' alive.id %}">Update</a>
                                                        <a type="button" class="btn " style = "background-color: #981D20"
                                                           href="{% url 'birds:delete_alive_birds_record' alive.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel"
                                 aria-labelledby="profile-tab">
                                <div class="table-responsive">
                                    <table class="table table-striped mb-0">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Quantity</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for deaths in dead_birds %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ deaths.birds_died }}</td>
                                                <td>{{ deaths.date.date }}</td>
                                                <td>
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <a type="button" class="btn " style="background-color: #F79824"
                                                           href="{% url 'birds:update_birds_deaths' deaths.id %}">Update</a>
                                                        <a type="button" class="btn btn-danger" style="background-color: #981D20"
                                                           href="{% url 'birds:delete_dead_birds_record' deaths.id %}">Delete</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end card-box -->
        </div> <!-- end col -->
    </div>




{% endblock %}

birds/templates/birds/generate_birds_slip.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1> Generate Birds Slip</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>From Date</label>
                                <input type="date" class="form-control" name="from_date" value="" required>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="date" class="form-control" name="to_date" value="" required>
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

birds/templates/birds/update_birds_death.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Update Birds Death Record</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>No of Birds</label>
                                <input type="text" class="form-control" name="no_of_birds" required
                                       required value="{{ update_record.birds_died }}">
                            </div>
                        </div><!-- end col -->


                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date" required
                                       value="{{ update_record.date |date:'Y-m-d'}}T{{update_record.date|time:'H:i:s'}}">
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

birds/templates/birds/update_more_alive_birds.html
{% extends 'baseTeamplate.html' %}
{% load static %}

{% block content %}
    <h1>Update Birds</h1>
    <div class="row">
        <div class="col-xl col-md">
            <div class="card-box ">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>No of Birds</label>
                                <input type="text" class="form-control" name="no_of_birds"
                                       required value="{{ update_record.birds_added }}">
                            </div>
                        </div><!-- end col -->


                        <div class="col-xl-6">
                            <div class="form-group">
                                <label>Date</label>
                                <input type="datetime-local" class="form-control" name="date" required
                                       value="{{ update_record.date |date:'Y-m-d'}}T{{update_record.date|time:'H:i:s'}}">
                            </div>
                            <button type="submit" class="btn btn-secondary float-right">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}